name: book_dat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  fluttertoast: ^8.1.1
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

